name: Despliegue aplicación de Unity

on:
  push:
    branches:
      - master  # Cambia a "master" si usas ese nombre

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Cambia esto si tu build genera otra carpeta